# SELECIONAR DATABASE
USE CARLOCA;

# CRIAR CLIENTE(NOME,IDADE,CPF(SOMENTE NUMEROS),LOGRADOURO,NUMERO,COMPLEMENTO,REFERENCIA) 
CALL CADASTRAR_CLIENTE('ROGERIO SILVA', 47, 12343254680, 'RUA TESTE', 123, '','');

# VERIFICAR CARROS DISPONIVELS
CALL VERIFICAR_CARROS_DISPONIVEIS();

# LOCAR CARRO(ID_CARRO, ID_CLIENTE, ID_UNIDADE_RETIRADA)
CALL LOCAR_CARRO(1,1,1);

# DEVOLVER CARRO(ID_CLIENTE, ID_UNIDADE_DEVOLUÇÃO, QUILOMETRAGEM_RODADA)alter
CALL DEVOLVER_CARRO(1,1,234);

# VERIFIAR HISTÓRICO (REGISTRO INSERIDO APÓS A DEVOLUÇÃO)
SELECT * FROM TBL_HIST_LOCACOES;
