USE CARLOCA;

DELIMITER $
CREATE TRIGGER TGR_LOCANDO_CARRO AFTER INSERT
ON TBL_LOCADOS
FOR EACH ROW
BEGIN
	UPDATE TBL_CARROS SET LOCADO = 'SIM' WHERE ID_CARRO = NEW.ID_CARRO;
END$

DELIMITER $$
CREATE TRIGGER TGR_DEVOLUCAO_CARRO AFTER DELETE
ON TBL_LOCADOS
FOR EACH ROW
BEGIN
	UPDATE TBL_CARROS SET LOCADO = 'NÃO' WHERE ID_CARRO = OLD.ID_CARRO;
END$$

DELIMITER $$$
CREATE PROCEDURE LOCAR_CARRO(IN ID_CARRO1 INT, IN ID_CLIENTE1 INT, IN ID_UNIDADE1 INT)
BEGIN
	IF((SELECT COUNT(*) FROM TBL_CARROS WHERE ID_CARRO = ID_CARRO1) = 1) THEN
		IF((SELECT LOCADO FROM TBL_CARROS WHERE ID_CARRO = ID_CARRO1) = 'NÃO') THEN
			IF((SELECT ATIVO FROM TBL_CARROS WHERE ID_CARRO = ID_CARRO1) = 'SIM') THEN
				IF((SELECT COUNT(*) FROM TBL_CLIENTES WHERE ID_CLIENTE = ID_CLIENTE1) = 1) THEN
					IF((SELECT COUNT(*) FROM TBL_LOCADOS WHERE ID_CLIENTE = ID_CLIENTE1) = 0) THEN
						IF((SELECT COUNT(*) FROM TBL_UNIDADES WHERE ID_UNIDADE = ID_UNIDADE1) = 1) THEN
							IF((SELECT ATIVO FROM TBL_UNIDADES WHERE ID_UNIDADE = ID_UNIDADE1) = 'SIM') THEN
								INSERT INTO TBL_LOCADOS(ID_CARRO, ID_CLIENTE, ID_UNIDADE_LOCACAO) VALUES (ID_CARRO1, ID_CLIENTE1, ID_UNIDADE1);
							ELSE
								SELECT 'Unidade de Locação está inativa no momento' AS FALHA;
							END IF;
						ELSE
							SELECT 'Unidade de Locação Inexistente' AS FALHA;
						END IF;
					ELSE
						SELECT 'Cliente já está com um carro locado' AS FALHA;
					END IF;
				ELSE
					SELECT 'Cliente Inexistente' AS FALHA;
				END IF;
			ELSE
				SELECT 'Carro está inativo no momento' AS FALHA;
			END IF;
		ELSE
			SELECT 'Carro já está locado' AS FALHA;
		END IF;
	ELSE
		SELECT 'Carro Inexistente' AS FALHA;
	END IF;
END$$$

DELIMITER $$$$
CREATE PROCEDURE DEVOLVER_CARRO(IN ID_CLIENTE1 INT, IN ID_UNIDADE_DEVOLUCAO1 INT, IN QUILOMETRAGEM_RODADA1 DOUBLE)
BEGIN
	IF((SELECT COUNT(*) FROM TBL_CLIENTES WHERE ID_CLIENTE = ID_CLIENTE1) = 1) THEN
		IF((SELECT COUNT(*) FROM TBL_LOCADOS WHERE ID_CLIENTE = ID_CLIENTE1) = 1) THEN
			IF((SELECT COUNT(*) FROM TBL_UNIDADES WHERE ID_UNIDADE = ID_UNIDADE_DEVOLUCAO1) = 1) THEN
				IF((SELECT ATIVO FROM TBL_UNIDADES WHERE ID_UNIDADE = ID_UNIDADE_DEVOLUCAO1) = 'SIM') THEN
					IF(QUILOMETRAGEM_RODADA1 > 0) THEN
						INSERT INTO TBL_HIST_LOCACOES(ID_CARRO, ID_CLIENTE, ID_UNIDADE_LOCACAO, ID_UNIDADE_DEVOLUCAO, DATA_LOCACAO, DATA_DEVOLUCAO, QUILOMATRAGEM_RODADA)
                        SELECT ID_CARRO, ID_CLIENTE, ID_UNIDADE_LOCACAO, ID_UNIDADE_DEVOLUCAO1, DATA_LOCACAO, CURRENT_TIMESTAMP, QUILOMETRAGEM_RODADA1
                        FROM TBL_LOCADOS
                        WHERE ID_CLIENTE = ID_CLIENTE1;
                        
                        UPDATE TBL_CARROS
							SET QUILOMETRAGEM_ATUAL = QUILOMETRAGEM_ATUAL + QUILOMETRAGEM_RODADA1
						WHERE ID_CARRO = (SELECT ID_CARRO FROM TBL_LOCADOS WHERE ID_CLIENTE = ID_CLIENTE1);
                        
                        DELETE FROM TBL_LOCADOS WHERE ID_CLIENTE = ID_CLIENTE1;
                    ELSE
						SELECT 'Quilometragem rodada deve ser maior que 0' AS FALHA;
                    END IF;
				ELSE
					SELECT 'Unidade de Devolução está inativa no momento' AS FALHA;
				END IF;
			ELSE
				SELECT 'Unidade de Devolução Inexistente' AS FALHA;
			END IF;
		ELSE
			SELECT 'Cliente não possui carro locado' AS FALHA;
		END IF;
	ELSE
		SELECT 'Cliente Inexistente' AS FALHA;
	END IF;
END$$$$

DELIMITER $$$$$
CREATE PROCEDURE VERIFICAR_CARROS_DISPONIVEIS()
BEGIN
	SELECT CAR.ID_CARRO, CAT.DESCRICAO CATEGORIA, MONT.DESCRICAO MONTADORA, CAR.MODELO, CAR.VERSAO, CAR.COR, CAR.QUILOMETRAGEM_ATUAL
    FROM TBL_CARROS AS CAR
		INNER JOIN TBL_CATEGORIAS AS CAT 
			ON CAR.ID_CATEGORIA = CAT.ID_CATEGORIA
		INNER JOIN TBL_MONTADORAS AS MONT
			ON CAR.ID_MONTADORA = MONT.ID_MONTADORA
    WHERE CAR.LOCADO = 'NÃO'
    ORDER BY CAR.ID_CARRO;
END$$$$$

DELIMITER $$$$$$
CREATE PROCEDURE CADASTRAR_CLIENTE(
	IN NOME VARCHAR(100), IN IDADE INT, IN CPF1 VARCHAR(14), IN LOGRADOURO VARCHAR(100), IN NUMERO VARCHAR(10), IN COMPLEMENTO VARCHAR(50), IN REFERENCIA VARCHAR(50))
BEGIN
	IF((SELECT COUNT(*) FROM TBL_CLIENTES WHERE CPF = CONCAT(SUBSTR(CPF1,1,3), '.', SUBSTR(CPF1,4,3), '.', SUBSTR(CPF1,7,3), '-', SUBSTR(CPF1,10,2))) >= 1) THEN
		SELECT 'CPF JÁ CADASTRADO' AS FALHA;
	ELSE
		INSERT INTO TBL_CLIENTES(NOME, IDADE, CPF, LOGRADOURO, NUMERO, COMPLEMENTO, REFERENCIA)
		VALUES (NOME, IDADE,CONCAT(SUBSTR(CPF1,1,3), '.', SUBSTR(CPF1,4,3), '.', SUBSTR(CPF1,7,3), '-', SUBSTR(CPF1,10,2)), LOGRADOURO, NUMERO, COMPLEMENTO, REFERENCIA);
	END IF;
END$$$$$$