CREATE DATABASE CARLOCA;
USE CARLOCA;

CREATE TABLE TBL_UNIDADES
(
ID_UNIDADE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRICAO VARCHAR(50) NOT NULL,
LOGRADOURO VARCHAR(100) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
COMPLEMENTO VARCHAR(50),
REFERENCIA VARCHAR(50),
ATIVO ENUM('SIM', 'NÃO') DEFAULT 'SIM' NOT NULL
);

CREATE TABLE TBL_MONTADORAS
(
ID_MONTADORA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE TBL_CATEGORIAS
(
ID_CATEGORIA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRICAO ENUM('HATCH', 'SEDAM COMPACTO', 'SEDAM MÉDIO', 'SUV') NOT NULL
);

CREATE TABLE TBL_CARROS
(
ID_CARRO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_MONTADORA INT NOT NULL,
ID_CATEGORIA INT NOT NULL,
MODELO VARCHAR(50) NOT NULL,
VERSAO DOUBLE NOT NULL,
COR ENUM('BRANCO', 'PRETO', 'PRATA') NOT NULL,
QUILOMETRAGEM_ATUAL DOUBLE NOT NULL,
ATIVO ENUM('SIM', 'NÃO') DEFAULT 'SIM' NOT NULL,
LOCADO ENUM('SIM', 'NÃO') DEFAULT 'NÃO' NOT NULL,
FOREIGN KEY (ID_MONTADORA) REFERENCES TBL_MONTADORAS(ID_MONTADORA),
FOREIGN KEY (ID_CATEGORIA) REFERENCES TBL_CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE TBL_CLIENTES
(
ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
IDADE INT NOT NULL,
CPF VARCHAR(14) NOT NULL,
LOGRADOURO VARCHAR(100) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
COMPLEMENTO VARCHAR(50),
REFERENCIA VARCHAR(50)
);

CREATE TABLE TBL_LOCADOS
(
ID_LOCACAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_CARRO INT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_UNIDADE_LOCACAO INT NOT NULL,
DATA_LOCACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
TIPO_LOCACAO ENUM('DIARIA') DEFAULT 'DIARIA' NOT NULL,
FOREIGN KEY(ID_CARRO) REFERENCES TBL_CARROS(ID_CARRO),
FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTES(ID_CLIENTE),
FOREIGN KEY(ID_UNIDADE_LOCACAO) REFERENCES TBL_UNIDADES(ID_UNIDADE)
);

CREATE TABLE TBL_HIST_LOCACOES
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_CARRO INT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_UNIDADE_LOCACAO INT NOT NULL,
ID_UNIDADE_DEVOLUCAO INT NOT NULL,
DATA_LOCACAO TIMESTAMP NOT NULL,
DATA_DEVOLUCAO TIMESTAMP NOT NULL,
QUILOMATRAGEM_RODADA DOUBLE NOT NULL,
FOREIGN KEY(ID_CARRO) REFERENCES TBL_CARROS(ID_CARRO),
FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTES(ID_CLIENTE),
FOREIGN KEY(ID_UNIDADE_LOCACAO) REFERENCES TBL_UNIDADES(ID_UNIDADE),
FOREIGN KEY(ID_UNIDADE_DEVOLUCAO) REFERENCES TBL_UNIDADES(ID_UNIDADE)
);